import type { CharacterSpec } from './types'

const modelUrl = (file: string) =>
  new URL(`../../../assets/models/${file}`, import.meta.url).href

export const CHARACTER_CATALOG: CharacterSpec[] = [
  {
    id: 'robototechnic',
    name: 'Robototechnic',
    price: 0,
    isDefault: true,
    isUnlockedByDefault: true,
    gameModelPath: modelUrl('robototechnic.glb'),
    shopModelPath: modelUrl('robototechnic_shop.glb'),
    gameScale: 0.9,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
  {
    id: 'granny',
    name: 'Granny',
    price: 150,
    gameModelPath: modelUrl('granny.glb'),
    shopModelPath: modelUrl('granny_shop.glb'),
    gameScale: 0.85,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
  {
    id: 'bigman',
    name: 'Big Man',
    price: 180,
    gameModelPath: modelUrl('bigman.glb'),
    shopModelPath: modelUrl('bigman_shop.glb'),
    gameScale: 0.9,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
  {
    id: 'greenwoman',
    name: 'Green Woman',
    price: 200,
    gameModelPath: modelUrl('greenwoman.glb'),
    shopModelPath: modelUrl('greenwoman_shop.glb'),
    gameScale: 0.88,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
  {
    id: 'mouse',
    name: 'Mouse',
    price: 160,
    gameModelPath: modelUrl('mouse.glb'),
    shopModelPath: modelUrl('mouse_shop.glb'),
    gameScale: 0.9,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
  {
    id: 'musculman',
    name: 'Musculman',
    price: 220,
    gameModelPath: modelUrl('musculman.glb'),
    shopModelPath: modelUrl('musculman_shop.glb'),
    gameScale: 0.9,
    gameRotationY: Math.PI,
    gameGroundOffset: 0.02,
    shopScale: 1.0,
    shopRotationY: Math.PI,
    shopGroundOffset: 0.02,
    gameAnimations: { run: ['run', 'walk'], idle: ['idle'], jump: ['jump'], slide: ['slide'] },
    shopAnimations: { run: ['run', 'walk'], idle: ['idle'] },
  },
]

export const DEFAULT_CHARACTER_ID =
  CHARACTER_CATALOG.find((c) => c.isDefault)?.id ?? 'robototechnic'

export function getCharacterById(id: string) {
  return CHARACTER_CATALOG.find((c) => c.id === id) ?? CHARACTER_CATALOG[0]
}
